"use strict";
var KEY="monAtelierCouture_v5";
var DEFAULT={
  profil:{mesures:{},styles:["bohème","naturel"]},
  palette:["#9c5d7c","#d9b8a3","#5b7152","#e8d9c0"],
  ai:{provider:"none",key:""},
  patImg:{},
  projets:[
    {id:1,name:"Jupe d'été en lin",piece:"Jupe",diff:"Facile",stat:"envie",tissu:"Lin moutarde, 1,5 m",date:""},
    {id:2,name:"Tote bag du marché",piece:"Sac",diff:"Facile",stat:"cours",tissu:"Toile coton écrue",date:""}
  ],
  inspirations:[],
  patrons:[],
  capsule:[
    {id:1,name:"Chemisier blanc",cat:"haut",color:"#f3efe7"},
    {id:2,name:"Jupe camel",cat:"bas",color:"#c79a6a"}
  ]
};
var state=load();
function load(){try{var r=localStorage.getItem(KEY);return r?Object.assign(JSON.parse(JSON.stringify(DEFAULT)),JSON.parse(r)):JSON.parse(JSON.stringify(DEFAULT));}catch(e){return JSON.parse(JSON.stringify(DEFAULT));}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){return false;}}
function uid(){return Date.now()+Math.floor(Math.random()*999);}
function toast(m){var t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(t._t);t._t=setTimeout(function(){t.classList.remove("show");},2300);}
function esc(s){return(s==null?"":String(s)).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
function jsq(s){return(s==null?"":String(s)).replace(/\\/g,"\\\\").replace(/'/g,"\\'");}
function $(id){return document.getElementById(id);}

function goView(v){document.querySelectorAll(".navbtn").forEach(function(n){n.classList.toggle("active",n.dataset.v===v);});document.querySelectorAll(".view").forEach(function(s){s.classList.toggle("active",s.id===v);});document.querySelectorAll("#stepper .s").forEach(function(s){s.classList.toggle("on",s.dataset.v===v);});window.scrollTo(0,0);}
document.querySelectorAll(".navbtn").forEach(function(b){b.addEventListener("click",function(){goView(b.dataset.v);});});
document.querySelectorAll("#stepper .s").forEach(function(b){b.addEventListener("click",function(){goView(b.dataset.v);});});

/* ===== CARNET ===== */
var carnetFilter="tous",carnetQuery="";
document.querySelectorAll("#carnetFilter button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#carnetFilter button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");carnetFilter=b.dataset.f;renderProjets();});});
$("carnetSearch").addEventListener("input",function(){carnetQuery=this.value.toLowerCase();renderProjets();});
var STAT={envie:"Envie",cours:"En cours",fini:"Terminé"};
function addProjet(){var name=$("pName").value.trim();if(!name){toast("Donne un nom au projet");return;}state.projets.unshift({id:uid(),name:name,piece:$("pPiece").value.trim(),diff:$("pDiff").value,stat:$("pStat").value,tissu:$("pTissu").value.trim(),date:$("pDate").value});save();["pName","pPiece","pTissu","pDate"].forEach(function(i){$(i).value="";});renderProjets();renderCarnetStats();toast("Projet ajouté au carnet");}
function delProjet(id){state.projets=state.projets.filter(function(p){return p.id!=id;});save();renderProjets();renderCarnetStats();}
function cycleStat(id){var o=["envie","cours","fini"];state.projets.forEach(function(p){if(p.id==id){p.stat=o[(o.indexOf(p.stat)+1)%3];}});save();renderProjets();renderCarnetStats();}
function renderCarnetStats(){var c={envie:0,cours:0,fini:0};state.projets.forEach(function(p){c[p.stat]++;});$("carnetStats").innerHTML=stat(c.envie,"Envies à coudre")+stat(c.cours,"En cours")+stat(c.fini,"Terminés");}
function stat(n,l){return '<div class="stat"><div class="n">'+n+'</div><div class="l">'+l+'</div></div>';}
function renderProjets(){var list=state.projets.filter(function(p){if(carnetFilter!="tous"&&p.stat!=carnetFilter)return false;if(carnetQuery){var h=((p.name||"")+" "+(p.piece||"")+" "+(p.tissu||"")).toLowerCase();if(h.indexOf(carnetQuery)<0)return false;}return true;});var el=$("projetList");if(!list.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;">Aucun projet ici pour l\'instant.</div>';return;}el.innerHTML=list.map(function(p){return '<div class="card"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:8px;"><div><h3 style="font-size:16px;">'+esc(p.name)+'</h3><div class="muted" style="font-size:13px;margin-top:2px;">'+(p.piece?esc(p.piece):"")+(p.piece&&p.diff?" &middot; ":"")+(p.diff?'<span class="tag diff">'+esc(p.diff)+'</span>':"")+'</div></div><button class="x" title="Supprimer" onclick="delProjet('+p.id+')">&times;</button></div>'+(p.tissu?'<div style="font-size:13.5px;margin-top:10px;">&#9763; '+esc(p.tissu)+'</div>':'')+(p.date?'<div class="muted" style="font-size:13px;margin-top:4px;">&#9200; pour le '+esc(p.date)+'</div>':'')+'<div style="margin-top:14px;"><button class="pill '+p.stat+'" onclick="cycleStat('+p.id+')" style="border:none;cursor:pointer;">'+STAT[p.stat]+' &#8635;</button></div></div>';}).join("");}

/* ===== INSPIRATIONS ===== */
document.querySelectorAll("#inspoMode button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#inspoMode button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");var m=b.dataset.m;$("inspoLink").style.display=m=="link"?"block":"none";$("inspoImage").style.display=m=="image"?"block":"none";$("inspoManual").style.display=m=="manual"?"block":"none";});});
function platformOf(url){var u=(url||"").toLowerCase();if(u.indexOf("instagram.")>=0||u.indexOf("instagr.am")>=0)return "Instagram";if(u.indexOf("pinterest.")>=0||u.indexOf("pin.it")>=0)return "Pinterest";if(u.indexOf("vinted.")>=0)return "Vinted";return "Web";}
function fetchHtml(url){return fetch("https://api.allorigins.win/get?url="+encodeURIComponent(url)).then(function(r){if(!r.ok)throw 0;return r.json();}).then(function(d){return d.contents;}).catch(function(){return fetch("https://corsproxy.io/?url="+encodeURIComponent(url)).then(function(r){if(!r.ok)throw 0;return r.text();});});}
function metaFrom(html){var doc=new DOMParser().parseFromString(html,"text/html");function pick(sel){var e=doc.querySelector(sel);return e?(e.getAttribute("content")||e.getAttribute("href")||""):"";}return {img:pick('meta[property="og:image"]')||pick('meta[name="twitter:image"]')||pick('meta[property="og:image:url"]')||pick('link[rel="image_src"]'),title:pick('meta[property="og:title"]')||(doc.querySelector("title")?doc.querySelector("title").textContent:"")||"",desc:pick('meta[property="og:description"]')||pick('meta[name="description"]')||""};}
function importLink(){var url=$("impUrl").value.trim();var st=$("impStatus"),pv=$("impPreview");pv.innerHTML="";if(!url){toast("Colle un lien d'abord");return;}if(!/^https?:\/\//.test(url))url="https://"+url;var plat=platformOf(url);st.innerHTML='<span class="spin"></span> Recherche de l\'aperçu sur '+plat+'…';fetchHtml(url).then(function(html){var m=metaFrom(html);window._pending={img:m.img,url:url,platform:plat};st.innerHTML=m.img?'Aperçu trouvé sur <span class="badge '+plat+'">'+plat+'</span> — ajuste et épingle.':'Pas d\'image trouvée, mais tu peux enregistrer le lien.';pv.innerHTML='<div class="card" style="display:flex;gap:14px;flex-wrap:wrap;align-items:flex-start;">'+(m.img?'<img src="'+esc(m.img)+'" style="width:130px;height:130px;object-fit:cover;border-radius:10px;border:1px solid var(--line);" onerror="this.style.display=\'none\'">':'')+'<div style="flex:1;min-width:200px;"><label class="fld">Titre</label><input id="pvTitle" type="text" value="'+esc((m.title||"").slice(0,90))+'"><label class="fld" style="margin-top:8px;">Note</label><input id="pvNote" type="text" value="'+esc((m.desc||"").slice(0,120))+'" placeholder="Ce qui te plaît..."><button class="btn" style="margin-top:12px;" onclick="savePending()">Épingler</button></div></div>';}).catch(function(){window._pending={img:"",url:url,platform:plat};st.innerHTML='Récupération auto impossible. Tu peux quand même enregistrer le lien.';pv.innerHTML='<div class="card"><label class="fld">Titre</label><input id="pvTitle" type="text" placeholder="Mon inspiration '+plat+'"><button class="btn" style="margin-top:12px;" onclick="savePending()">Enregistrer le lien</button></div>';});}
function savePending(){var p=window._pending||{};var title=($("pvTitle")||{}).value||"Inspiration "+(p.platform||"");var note=($("pvNote")||{}).value||"";var obj={id:uid(),title:(title.trim()||("Inspiration "+(p.platform||""))),img:p.img||"",note:note.trim(),url:p.url||"",platform:p.platform||"Web",tags:[]};state.inspirations.unshift(obj);save();$("impUrl").value="";$("impStatus").innerHTML="";$("impPreview").innerHTML="";window._pending=null;renderInspo();refreshRefSelect();autoTag(obj);toast("Inspiration épinglée");}
function addInspoManual(){var t=$("iTitle").value.trim();if(!t){toast("Donne un titre");return;}var obj={id:uid(),title:t,img:$("iImg").value.trim(),note:$("iNote").value.trim(),url:"",platform:"Manuel",tags:[]};state.inspirations.unshift(obj);save();["iTitle","iImg","iNote"].forEach(function(i){$(i).value="";});renderInspo();autoTag(obj);toast("Inspiration épinglée");}
var dz=$("dropz");
dz.addEventListener("click",function(){$("imgFile").click();});
dz.addEventListener("dragover",function(e){e.preventDefault();dz.classList.add("drag");});
dz.addEventListener("dragleave",function(){dz.classList.remove("drag");});
dz.addEventListener("drop",function(e){e.preventDefault();dz.classList.remove("drag");handleImgFiles(e.dataTransfer.files);});
$("imgFile").addEventListener("change",function(){handleImgFiles(this.files);this.value="";});
function handleImgFiles(files){var arr=[].slice.call(files).filter(function(f){return f.type.indexOf("image")===0;});if(!arr.length)return;var done=0;arr.forEach(function(f){var rd=new FileReader();rd.onload=function(){var img=new Image();img.onload=function(){var max=760,w=img.width,h=img.height;if(w>max||h>max){var r=Math.min(max/w,max/h);w=Math.round(w*r);h=Math.round(h*r);}var cv=document.createElement("canvas");cv.width=w;cv.height=h;cv.getContext("2d").drawImage(img,0,0,w,h);var data=cv.toDataURL("image/jpeg",0.72);var obj={id:uid(),title:(f.name||"Image").replace(/\.[^.]+$/,""),img:data,note:"",url:"",platform:"Image",tags:[]};state.inspirations.unshift(obj);if(!save()){state.inspirations.shift();toast("Mémoire pleine — exporte/allège tes images");}else{autoTag(obj);}done++;if(done===arr.length){renderInspo();refreshRefSelect();toast(arr.length>1?arr.length+" images ajoutées":"Image ajoutée");}};img.src=rd.result;};rd.readAsDataURL(f);});}
function delInspo(id){state.inspirations=state.inspirations.filter(function(x){return x.id!=id;});save();renderInspo();refreshRefSelect();}
function inspoToProjet(id){var x=state.inspirations.filter(function(i){return i.id==id;})[0];if(!x)return;state.projets.unshift({id:uid(),name:x.title,piece:"",diff:"Facile",stat:"envie",tissu:x.note||"",date:""});save();renderProjets();renderCarnetStats();toast("Ajouté au carnet comme projet");}
/* tags */
var activeTags=[];
function allTags(){var s={};state.inspirations.forEach(function(x){(x.tags||[]).forEach(function(t){s[t]=(s[t]||0)+1;});});return Object.keys(s).sort(function(a,b){return s[b]-s[a];});}
function renderTagFilter(){var tags=allTags();var el=$("tagFilter");if(!tags.length){el.innerHTML="";return;}el.innerHTML='<span class="muted" style="font-size:12.5px;margin-right:6px;">Filtrer :</span>'+tags.map(function(t){return '<span class="tchip'+(activeTags.indexOf(t)<0?" off":"")+'" onclick="toggleTag(\''+jsq(t)+'\')">'+esc(t)+'</span>';}).join("")+(activeTags.length?' <span class="tchip" style="background:var(--surface2);color:var(--accent-ink);" onclick="clearTags()">&times; tout</span>':"");}
function toggleTag(t){var i=activeTags.indexOf(t);if(i<0)activeTags.push(t);else activeTags.splice(i,1);renderTagFilter();renderInspo();}
function clearTags(){activeTags=[];renderTagFilter();renderInspo();}
function editTags(id){var x=state.inspirations.filter(function(i){return i.id==id;})[0];if(!x)return;var v=prompt("Tags (séparés par des virgules) :",(x.tags||[]).join(", "));if(v===null)return;x.tags=v.split(",").map(function(s){return s.trim().toLowerCase();}).filter(function(s){return s;});save();renderInspo();renderTagFilter();}
function autoTag(x){var prov=(state.ai&&state.ai.provider)||"none";if(prov!=="none"&&state.ai.key&&x.img){visionTags(x.img).then(function(t){x.tags=t;save();renderInspo();renderTagFilter();}).catch(function(){x.tags=textTags(x);save();renderInspo();renderTagFilter();});}else{x.tags=textTags(x);save();renderTagFilter();}}
function tagInspo(id){var x=state.inspirations.filter(function(i){return i.id==id;})[0];if(!x)return;var prov=(state.ai&&state.ai.provider)||"none";if(prov!=="none"&&state.ai.key&&x.img){toast("Analyse de l'image…");visionTags(x.img).then(function(tags){x.tags=tags;save();renderInspo();renderTagFilter();toast("Tags ajoutés");}).catch(function(){x.tags=textTags(x);save();renderInspo();renderTagFilter();toast("Vision indispo — tags texte");});}else{x.tags=textTags(x);save();renderInspo();renderTagFilter();toast(prov==="none"?"Tags depuis le texte (ajoute une clé pour l'image)":"Pas d'image — tags texte");}}
function tagAllInspo(){var prov=(state.ai&&state.ai.provider)||"none";var imgs=state.inspirations.filter(function(x){return x.img&&(!x.tags||!x.tags.length);});if(prov==="none"||!state.ai.key){state.inspirations.forEach(function(x){if(!x.tags||!x.tags.length)x.tags=textTags(x);});save();renderInspo();renderTagFilter();toast("Tags depuis le texte (ajoute une clé pour les images)");return;}if(!imgs.length){toast("Rien à tagger");return;}toast("Analyse de "+imgs.length+" image(s)…");var i=0;function next(){if(i>=imgs.length){save();renderInspo();renderTagFilter();toast("Tagging terminé");return;}var x=imgs[i++];visionTags(x.img).then(function(t){x.tags=t;}).catch(function(){x.tags=textTags(x);}).then(function(){renderInspo();next();});}next();}
function textTags(x){var d=detect((x.title||"")+" "+(x.note||""));var t=[].concat(d.color,d.garment,d.detail,d.style);return t.filter(function(v,i){return t.indexOf(v)===i;}).slice(0,10);}
function visionTags(imgUrl){var prompt="Décris ce vêtement par 8 à 12 tags courts en français : couleur(s), type (robe, jupe, top, pantalon...), longueur, coupe/silhouette, encolure, manches, motif, style. Réponds UNIQUEMENT par les tags séparés par des virgules, en minuscules.";return callVision(prompt,imgUrl).then(function(txt){return txt.replace(/\n/g,",").split(",").map(function(s){return s.trim().toLowerCase().replace(/^[-•\d.\)]+\s*/,"");}).filter(function(s){return s&&s.length<28;}).filter(function(v,i,a){return a.indexOf(v)===i;}).slice(0,12);});}
function renderInspo(){var el=$("inspoList");$("inspoCount").textContent=state.inspirations.length?state.inspirations.length+" inspiration(s)":"";var list=state.inspirations.filter(function(x){if(!activeTags.length)return true;var tg=x.tags||[];return activeTags.every(function(t){return tg.indexOf(t)>=0;});});if(!list.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;">'+(state.inspirations.length?"Aucune inspiration pour ces tags.":"Importe ta première inspiration : un lien Pinterest/Instagram/Vinted, ou une image.")+'</div>';return;}el.innerHTML=list.map(function(x){var ph=x.img?'<div class="ph" style="background-image:url(\''+(x.img.indexOf("data:")===0?x.img:esc(x.img))+'\')"></div>':'<div class="ph">&#10047; pas d\'image</div>';var src=x.url?'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">source &#8599;</a>':'';var tags=(x.tags||[]).map(function(t){return '<span class="tchip" onclick="toggleTag(\''+jsq(t)+'\')">'+esc(t)+'</span>';}).join("");return '<div class="insp">'+ph+'<div class="bd"><div style="display:flex;justify-content:space-between;align-items:center;gap:6px;"><span class="badge '+(x.platform||"Manuel")+'">'+esc(x.platform||"Manuel")+'</span><button class="x" onclick="delInspo('+x.id+')">&times;</button></div><h4>'+esc(x.title)+'</h4>'+(x.note?'<div class="muted" style="font-size:13px;">'+esc(x.note)+'</div>':'')+(tags?'<div style="margin-top:8px;">'+tags+'</div>':'')+'<div style="margin-top:10px;display:flex;gap:8px;align-items:center;font-size:13px;flex-wrap:wrap;"><button class="btn ghost sm" onclick="tagInspo('+x.id+')">Tags IA</button><button class="btn ghost sm" onclick="editTags('+x.id+')">&#9998;</button><button class="btn ghost sm" onclick="inspoToProjet('+x.id+')">&#8594; projet</button>'+src+'</div></div></div>';}).join("");}
function renderPalette(){var el=$("paletteRow");el.innerHTML=state.palette.map(function(c,i){return '<div style="text-align:center;"><div class="swatch" style="background:'+c+'"></div><button class="x" style="font-size:13px;" onclick="delColor('+i+')">retirer</button></div>';}).join("")+'<label class="btn ghost sm" style="cursor:pointer;">+ couleur<input type="color" style="display:none;" onchange="addColor(this.value)"></label>';renderPaletteQuick();renderSketchPalette();}
function addColor(c){state.palette.push(c);save();renderPalette();}
function delColor(i){state.palette.splice(i,1);save();renderPalette();}

/* ===== IA ===== */
var LEX={style:["bohème","boho","minimaliste","vintage","rétro","romantique","casual","chic","sportif","streetwear","cottagecore","preppy","gothique","classique","moderne","élégant","oversize","ample","fluide","structuré","naturel","scandinave","parisien"],garment:{robe:"robe",robes:"robe",dress:"robe",jupe:"jupe",skirt:"jupe",top:"top",blouse:"blouse",chemise:"chemise",shirt:"chemise",pantalon:"pantalon",pants:"pantalon",jean:"jean",short:"short",veste:"veste",jacket:"veste",manteau:"manteau",coat:"manteau",combinaison:"combinaison",pull:"pull","t-shirt":"t-shirt",tshirt:"t-shirt",gilet:"gilet",cardigan:"cardigan"},fabric:["lin","coton","laine","soie","velours","jean","denim","viscose","satin","crêpe","jersey","maille","tweed","gaze","mousseline","cuir","liberty","popeline"],detail:["manches ballon","manches longues","sans manche","col v","col claudine","encolure","fronces","plis","volants","boutons","ceinture","poches","taille haute","dos nu","smocks","broderie","asymétrique","portefeuille"],color:["beige","écru","blanc","noir","bleu","marine","vert","kaki","rouge","bordeaux","rose","moutarde","jaune","ocre","terracotta","camel","gris","violet","corail","pastel"]};
function detect(text){var c=(text||corpus()).toLowerCase();var res={style:[],garment:[],fabric:[],detail:[],color:[]};LEX.style.forEach(function(w){if(c.indexOf(w)>=0&&res.style.indexOf(w)<0)res.style.push(w);});Object.keys(LEX.garment).forEach(function(w){if(c.indexOf(w)>=0){var g=LEX.garment[w];if(res.garment.indexOf(g)<0)res.garment.push(g);}});LEX.fabric.forEach(function(w){if(c.indexOf(w)>=0&&res.fabric.indexOf(w)<0)res.fabric.push(w);});LEX.detail.forEach(function(w){if(c.indexOf(w)>=0&&res.detail.indexOf(w)<0)res.detail.push(w);});LEX.color.forEach(function(w){if(c.indexOf(w)>=0&&res.color.indexOf(w)<0)res.color.push(w);});return res;}
function corpus(){var t=[];state.inspirations.forEach(function(x){t.push((x.title||"")+" "+(x.note||"")+" "+((x.tags||[]).join(" ")));});(state.profil.styles||[]).forEach(function(s){t.push(s);});return t.join(" ").toLowerCase();}
function heuristicReport(){var d=detect(),n=state.inspirations.length;if(!n&&!(state.profil.styles||[]).length){return '<div class="empty">Ajoute d\'abord quelques inspirations (onglet 1), puis reviens ici.</div>';}var styles=d.style.length?d.style.slice(0,5):(state.profil.styles||["à préciser"]);var garments=d.garment.length?d.garment:["robe","jupe","top"];var fabrics=d.fabric.length?d.fabric:["lin","coton"];var details=d.detail.length?d.detail:["fronces","manches courtes"];function pick(a,i){return a[i%a.length];}var ideas=[];for(var i=0;i<3;i++){ideas.push((i+1)+". Une "+pick(garments,i)+" "+pick(styles,i)+" en "+pick(fabrics,i)+", avec "+pick(details,i)+".");}var sw=state.palette.map(function(c){return '<span class="swatch" style="display:inline-block;width:24px;height:24px;background:'+c+';vertical-align:middle;margin-right:5px;"></span>';}).join("");var html='<div class="card" style="background:var(--accent-soft);border:none;margin-bottom:16px;"><div style="font-size:13px;color:var(--accent-ink);font-weight:600;letter-spacing:.4px;text-transform:uppercase;">Ton profil de style</div><div style="font-size:19px;font-weight:600;margin-top:4px;color:var(--accent-ink);">'+styles.slice(0,4).join(" &middot; ")+'</div><div class="muted" style="font-size:13px;margin-top:4px;">d\'après '+n+' inspiration(s)</div></div>';html+='<div class="ai-out">';html+="Vêtements qui reviennent : "+garments.join(", ")+".\n";if(d.fabric.length)html+="Matières évoquées : "+fabrics.join(", ")+".\n";if(d.detail.length)html+="Détails repérés : "+details.join(", ")+".\n";html+="\nPalette : "+sw+"\n\n";html+="3 pistes à dessiner :\n"+ideas.join("\n");html+="\n\nProchaine étape : ouvre le Studio pour mettre en forme la première idée.";html+='</div>';html+='<div style="margin-top:14px;display:flex;gap:8px;flex-wrap:wrap;"><button class="btn sm" onclick="goView(\'studio\')">Ouvrir le Studio</button><button class="btn ghost sm" onclick="goView(\'patrons\')">Voir des patrons</button></div>';return html;}
function saveAiKey(){state.ai={provider:$("aiProvider").value,key:$("aiKey").value.trim()};save();toast(state.ai.provider==="none"?"Mode local activé":"Clé enregistrée (sur cet appareil)");updateAiMode();}
function updateAiMode(){var p=(state.ai&&state.ai.provider)||"none";$("aiMode").textContent=p==="none"?"Mode : analyse locale":"Mode : IA "+p;if($("aiProvider"))$("aiProvider").value=p;if($("aiKey"))$("aiKey").value=(state.ai&&state.ai.key)||"";}
function runAssistant(){var out=$("aiResult");var p=(state.ai&&state.ai.provider)||"none";if(p==="none"||!(state.ai&&state.ai.key)){out.innerHTML=heuristicReport();return;}out.innerHTML='<div class="muted"><span class="spin"></span> L\'IA réfléchit à tes inspirations…</div>';var pr="Tu es styliste. Voici les inspirations couture (titres/notes/tags) et mots-clés de style :\n"+corpus().slice(0,1500)+"\n\nEn français, concis : 1) profil de style en 3-4 mots-clés, 2) vêtements et matières récurrents, 3) trois idées de créations précises (vêtement + coupe + tissu + détail). Format clair.";callText(pr).then(function(txt){out.innerHTML=heuristicReport()+'<div class="card" style="margin-top:16px;"><div style="font-size:13px;color:var(--accent-ink);font-weight:600;text-transform:uppercase;letter-spacing:.4px;margin-bottom:8px;">Idées rédigées par l\'IA</div><div class="ai-out">'+esc(txt)+'</div></div>';}).catch(function(err){out.innerHTML=heuristicReport()+'<div class="muted" style="margin-top:14px;font-size:13px;">Appel IA échoué ('+esc(String(err).slice(0,80))+'). Analyse locale ci-dessus.</div>';});}
function callText(prompt){var prov=state.ai.provider,key=state.ai.key;if(prov==="openai")return fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:"gpt-4o-mini",messages:[{role:"user",content:prompt}],max_tokens:600})}).then(function(r){return r.json();}).then(function(d){if(d.error)throw d.error.message;return d.choices[0].message.content;});if(prov==="anthropic")return fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:"claude-3-5-haiku-latest",max_tokens:600,messages:[{role:"user",content:prompt}]})}).then(function(r){return r.json();}).then(function(d){if(d.error)throw d.error.message;return d.content[0].text;});return Promise.reject("fournisseur");}
function callVision(prompt,imgUrl){var prov=state.ai.provider,key=state.ai.key;if(prov==="openai")return fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:"gpt-4o-mini",max_tokens:200,messages:[{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:imgUrl}}]}]})}).then(function(r){return r.json();}).then(function(d){if(d.error)throw d.error.message;return d.choices[0].message.content;});if(prov==="anthropic"){var srcObj;var mm=imgUrl.match(/^data:(.*?);base64,(.*)$/);if(mm)srcObj={type:"base64",media_type:mm[1],data:mm[2]};else srcObj={type:"url",url:imgUrl};return fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:"claude-3-5-haiku-latest",max_tokens:200,messages:[{role:"user",content:[{type:"image",source:srcObj},{type:"text",text:prompt}]}]})}).then(function(r){return r.json();}).then(function(d){if(d.error)throw d.error.message;return d.content[0].text;});}return Promise.reject("fournisseur");}

/* ===== STUDIO compose ===== */
var design={type:"robe",sil:"droite",len:"genou",neck:"ras",sleeve:"courte",hem:"simple",waist:"aucun",poches:false,boutons:false,fente:false,print:"uni",color:"#9c5d7c",view:"devant"};
document.querySelectorAll("#studioMode button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#studioMode button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");var s=b.dataset.s;$("studioCompose").style.display=s=="compose"?"block":"none";$("studioDraw").style.display=s=="draw"?"block":"none";if(s=="draw")initSketch();});});
function renderPaletteQuick(){var el=$("dPaletteQuick");if(!el)return;el.innerHTML=state.palette.map(function(c){return '<button class="swatch" style="width:26px;height:26px;background:'+c+';cursor:pointer;" title="utiliser" onclick="setDesignColor(\''+c+'\')"></button>';}).join("");}
function setDesignColor(c){design.color=c;$("dColor").value=c;drawDesign();}
document.querySelectorAll("#dType button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#dType button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");design.type=b.dataset.t;var topish=(design.type=="robe"||design.type=="top");$("dNeckWrap").style.display=topish?"block":"none";$("dSleeveWrap").style.display=topish?"block":"none";drawDesign();});});
document.querySelectorAll("#dPrint button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#dPrint button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");design.print=b.dataset.p;drawDesign();});});
document.querySelectorAll("#dViewSeg button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#dViewSeg button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");design.view=b.dataset.w;drawDesign();});});
["dSil","dLen","dNeck","dSleeve","dHem","dWaist"].forEach(function(id){var e=$(id);if(e)e.addEventListener("change",readDesign);});
["dPoches","dBoutons","dFente"].forEach(function(id){var e=$(id);if(e)e.addEventListener("change",readDesign);});
$("dColor").addEventListener("input",function(){design.color=this.value;drawDesign();});
function readDesign(){design.sil=$("dSil").value;design.len=$("dLen").value;design.neck=$("dNeck").value;design.sleeve=$("dSleeve").value;design.hem=$("dHem").value;design.waist=$("dWaist").value;design.poches=$("dPoches").checked;design.boutons=$("dBoutons").checked;design.fente=$("dFente").checked;drawDesign();}
function printDefs(print,color){if(print=="uni")return {fill:color,defs:""};var d="";if(print=="pois")d='<pattern id="pat" width="20" height="20" patternUnits="userSpaceOnUse"><rect width="20" height="20" fill="'+color+'"/><circle cx="5" cy="5" r="2.4" fill="#ffffff" fill-opacity="0.65"/><circle cx="15" cy="15" r="2.4" fill="#ffffff" fill-opacity="0.65"/></pattern>';else if(print=="rayures")d='<pattern id="pat" width="16" height="10" patternUnits="userSpaceOnUse"><rect width="16" height="10" fill="'+color+'"/><rect width="8" height="10" fill="#ffffff" fill-opacity="0.35"/></pattern>';else d='<pattern id="pat" width="26" height="26" patternUnits="userSpaceOnUse"><rect width="26" height="26" fill="'+color+'"/><g fill="#ffffff" fill-opacity="0.6"><circle cx="8" cy="8" r="2"/><circle cx="12" cy="6" r="2"/><circle cx="10" cy="11" r="2"/><circle cx="20" cy="19" r="2"/><circle cx="24" cy="17" r="2"/><circle cx="22" cy="22" r="2"/></g></pattern>';return {fill:"url(#pat)",defs:d};}
function detailOverlays(C,waistY,hemY,halfW,halfH,applyHem){
  var st="#5a4a52",o="";
  if(design.waist=="ceinture")o+='<rect x="'+(C-halfW)+'" y="'+(waistY-5)+'" width="'+(halfW*2)+'" height="10" fill="rgba(90,74,82,0.5)" stroke="'+st+'" stroke-width="1.4"/>';
  else if(design.waist=="noeud")o+='<path d="M '+C+' '+waistY+' l -16 -8 l 0 16 z" fill="rgba(90,74,82,0.55)" stroke="'+st+'" stroke-width="1.2"/><path d="M '+C+' '+waistY+' l 16 -8 l 0 16 z" fill="rgba(90,74,82,0.55)" stroke="'+st+'" stroke-width="1.2"/><rect x="'+(C-3)+'" y="'+(waistY-4)+'" width="6" height="8" fill="'+st+'"/>';
  if(design.boutons){o+='<line x1="'+C+'" y1="'+(waistY-44)+'" x2="'+C+'" y2="'+(hemY-12)+'" stroke="'+st+'" stroke-width="1" stroke-dasharray="2 3"/>';for(var by=waistY-36;by<hemY-12;by+=20)o+='<circle cx="'+C+'" cy="'+by+'" r="2" fill="'+st+'"/>';}
  if(design.poches){var py=waistY+18;o+='<rect x="'+(C-halfW*0.5-20)+'" y="'+py+'" width="20" height="22" rx="3" fill="none" stroke="'+st+'" stroke-width="1.4"/><rect x="'+(C+halfW*0.5)+'" y="'+py+'" width="20" height="22" rx="3" fill="none" stroke="'+st+'" stroke-width="1.4"/>';}
  if(design.fente)o+='<line x1="'+C+'" y1="'+(hemY-48)+'" x2="'+C+'" y2="'+(hemY-2)+'" stroke="'+st+'" stroke-width="2"/>';
  if(applyHem){
    if(design.hem=="volante"){o+='<path d="M '+(C-halfH)+' '+(hemY-14)+' ';for(var x=C-halfH;x<C+halfH;x+=18){o+='q 9 12 18 0 ';}o+='" fill="none" stroke="'+st+'" stroke-width="1.4" opacity="0.8"/>';}
    else if(design.hem=="plisse"){for(var px=C-halfH+12;px<C+halfH-8;px+=15)o+='<line x1="'+px+'" y1="'+(hemY-80)+'" x2="'+px+'" y2="'+(hemY-4)+'" stroke="'+st+'" stroke-width="1" opacity="0.45"/>';}
    else if(design.hem=="asymetrique")o+='<line x1="'+(C-halfH)+'" y1="'+(hemY-34)+'" x2="'+(C+halfH)+'" y2="'+(hemY+20)+'" stroke="'+st+'" stroke-width="2"/>';
    else if(design.hem=="portefeuille")o+='<line x1="'+(C-halfH*0.2)+'" y1="'+waistY+'" x2="'+(C+halfH*0.7)+'" y2="'+(hemY-4)+'" stroke="'+st+'" stroke-width="1.6" stroke-dasharray="5 3"/>';
  }
  return o;
}
function drawDesign(){
  var svg=$("designSvg");var C=150;var pf=printDefs(design.print,design.color);var stroke="#5a4a52";var parts="";var lenMap={mini:0,genou:1,midi:2,long:3};var topish=(design.type=="robe"||design.type=="top");var dos=(design.view=="dos");
  function poly(pts){return "M"+pts.map(function(p){return p[0].toFixed(1)+" "+p[1].toFixed(1);}).join(" L ")+" Z";}
  if(topish){
    var shoulderY=92,bustY=150,waistY=205,hipY=240,shoulderHalf=58,bustHalf=50;
    var waistHalf=design.sil=="ajustee"?38:(design.sil=="ample"?60:48);
    var hipHalf=design.sil=="ajustee"?52:(design.sil=="ample"?64:54);
    var hemY,hemHalf;if(design.type=="top"){hemY=[185,225,255,280][lenMap[design.len]];}else{hemY=[300,355,400,448][lenMap[design.len]];}
    if(design.sil=="droite")hemHalf=waistHalf+4;else if(design.sil=="evasee")hemHalf=(design.type=="top"?bustHalf+30:waistHalf+58);else if(design.sil=="ajustee")hemHalf=hipHalf-2;else hemHalf=72;
    var neckHalf,neckPath,nk=dos?"rasdos":design.neck;
    if(nk=="ras"){neckHalf=18;neckPath="Q "+C+" "+(shoulderY+16)+" "+(C-neckHalf)+" "+shoulderY;}
    else if(nk=="rasdos"){neckHalf=18;neckPath="Q "+C+" "+(shoulderY+7)+" "+(C-neckHalf)+" "+shoulderY;}
    else if(nk=="v"){neckHalf=18;neckPath="L "+C+" "+(shoulderY+46)+" L "+(C-neckHalf)+" "+shoulderY;}
    else if(nk=="bateau"){neckHalf=32;neckPath="Q "+C+" "+(shoulderY+8)+" "+(C-neckHalf)+" "+shoulderY;}
    else {neckHalf=22;neckPath="L "+(C-neckHalf)+" "+(shoulderY+26)+" L "+(C+neckHalf)+" "+(shoulderY+26)+" L "+(C+neckHalf)+" "+shoulderY;}
    var carre=(nk=="carre");var body=[];
    body.push([C-shoulderHalf,shoulderY]);body.push([C-bustHalf,bustY]);body.push([C-waistHalf,waistY]);if(design.type!="top")body.push([C-hipHalf,hipY]);body.push([C-hemHalf,hemY]);body.push([C+hemHalf,hemY]);if(design.type!="top")body.push([C+hipHalf,hipY]);body.push([C+waistHalf,waistY]);body.push([C+bustHalf,bustY]);body.push([C+shoulderHalf,shoulderY]);
    var bodyPath;
    if(carre){bodyPath="M "+(C-shoulderHalf)+" "+shoulderY+" L "+(C-bustHalf)+" "+bustY+" L "+(C-waistHalf)+" "+waistY+(design.type!="top"?" L "+(C-hipHalf)+" "+hipY:"")+" L "+(C-hemHalf)+" "+hemY+" L "+(C+hemHalf)+" "+hemY+(design.type!="top"?" L "+(C+hipHalf)+" "+hipY:"")+" L "+(C+waistHalf)+" "+waistY+" L "+(C+bustHalf)+" "+bustY+" L "+(C+shoulderHalf)+" "+shoulderY+" L "+(C+neckHalf)+" "+shoulderY+" L "+(C+neckHalf)+" "+(shoulderY+26)+" L "+(C-neckHalf)+" "+(shoulderY+26)+" L "+(C-neckHalf)+" "+shoulderY+" Z";}
    else { bodyPath=poly(body).slice(0,-2)+" L "+(C+neckHalf)+" "+shoulderY+" "+neckPath+" Z"; }
    var sl="";
    if(design.sleeve!="sans"){
      if(design.sleeve=="courte"||design.sleeve=="flutter"){var ext=design.sleeve=="flutter"?34:26,dy=design.sleeve=="flutter"?22:10;sl+='<path d="M '+(C-shoulderHalf)+' '+shoulderY+' L '+(C-shoulderHalf-ext)+' '+(shoulderY+dy)+' L '+(C-shoulderHalf-ext+6)+' '+(bustY-6)+' L '+(C-bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';sl+='<path d="M '+(C+shoulderHalf)+' '+shoulderY+' L '+(C+shoulderHalf+ext)+' '+(shoulderY+dy)+' L '+(C+shoulderHalf+ext-6)+' '+(bustY-6)+' L '+(C+bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';if(design.sleeve=="flutter"){sl+='<path d="M '+(C-shoulderHalf-ext)+' '+(shoulderY+dy)+' q 6 10 '+(ext-6)+' '+(bustY-6-shoulderY-dy)+'" fill="none" stroke="'+stroke+'" stroke-width="1" opacity="0.5"/>';}}
      else if(design.sleeve=="longue"){sl+='<path d="M '+(C-shoulderHalf)+' '+shoulderY+' L '+(C-shoulderHalf-24)+' '+(shoulderY+8)+' L '+(C-shoulderHalf-14)+' 250 L '+(C-shoulderHalf+4)+' 250 L '+(C-bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';sl+='<path d="M '+(C+shoulderHalf)+' '+shoulderY+' L '+(C+shoulderHalf+24)+' '+(shoulderY+8)+' L '+(C+shoulderHalf+14)+' 250 L '+(C+shoulderHalf-4)+' 250 L '+(C+bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';}
      else if(design.sleeve=="bishop"){sl+='<path d="M '+(C-shoulderHalf)+' '+shoulderY+' C '+(C-shoulderHalf-46)+' '+(shoulderY+40)+' '+(C-shoulderHalf-40)+' 230 '+(C-shoulderHalf-2)+' 252 L '+(C-shoulderHalf+12)+' 250 L '+(C-bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';sl+='<path d="M '+(C+shoulderHalf)+' '+shoulderY+' C '+(C+shoulderHalf+46)+' '+(shoulderY+40)+' '+(C+shoulderHalf+40)+' 230 '+(C+shoulderHalf+2)+' 252 L '+(C+shoulderHalf-12)+' 250 L '+(C+bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';}
      else {sl+='<path d="M '+(C-shoulderHalf)+' '+shoulderY+' C '+(C-shoulderHalf-40)+' '+(shoulderY+6)+' '+(C-shoulderHalf-40)+' '+(bustY-2)+' '+(C-bustHalf-6)+' '+(bustY+6)+' L '+(C-bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';sl+='<path d="M '+(C+shoulderHalf)+' '+shoulderY+' C '+(C+shoulderHalf+40)+' '+(shoulderY+6)+' '+(C+shoulderHalf+40)+' '+(bustY-2)+' '+(C+bustHalf+6)+' '+(bustY+6)+' L '+(C+bustHalf)+' '+bustY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2"/>';}
    }
    parts=sl+'<path d="'+bodyPath+'" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2.2" stroke-linejoin="round"/>';
    if(dos){parts+='<line x1="'+C+'" y1="'+(shoulderY+6)+'" x2="'+C+'" y2="'+(hemY-6)+'" stroke="'+stroke+'" stroke-width="1.2" stroke-dasharray="2 3" opacity="0.6"/><circle cx="'+C+'" cy="'+(shoulderY+14)+'" r="2.4" fill="none" stroke="'+stroke+'" stroke-width="1.2"/>';}
    else{parts+='<line x1="'+C+'" y1="'+(shoulderY+28)+'" x2="'+C+'" y2="'+(hemY-6)+'" stroke="'+stroke+'" stroke-width="1" stroke-dasharray="3 4" opacity="0.45"/>';}
    parts+='<line x1="'+(C-hemHalf+4)+'" y1="'+(hemY-5)+'" x2="'+(C+hemHalf-4)+'" y2="'+(hemY-5)+'" stroke="'+stroke+'" stroke-width="1" stroke-dasharray="2 3" opacity="0.5"/>';
    parts+=detailOverlays(C,waistY,hemY,waistHalf,hemHalf,true);
  } else if(design.type=="jupe"){
    var wY=150,hemY2=[235,300,360,440][lenMap[design.len]];var wHalf=design.sil=="ample"?60:48,hemHalf2;
    if(design.sil=="droite")hemHalf2=wHalf+2;else if(design.sil=="evasee")hemHalf2=wHalf+62;else if(design.sil=="ajustee")hemHalf2=wHalf+10;else hemHalf2=82;
    parts='<rect x="'+(C-wHalf)+'" y="'+(wY-16)+'" width="'+(wHalf*2)+'" height="16" rx="3" fill="'+design.color+'" stroke="'+stroke+'" stroke-width="2"/>';
    parts+='<path d="M '+(C-wHalf)+' '+wY+' L '+(C-hemHalf2)+' '+hemY2+' L '+(C+hemHalf2)+' '+hemY2+' L '+(C+wHalf)+' '+wY+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2.2" stroke-linejoin="round"/>';
    if(dos)parts+='<line x1="'+C+'" y1="'+(wY-16)+'" x2="'+C+'" y2="'+(hemY2-6)+'" stroke="'+stroke+'" stroke-width="1.2" stroke-dasharray="2 3" opacity="0.6"/>';
    parts+='<line x1="'+(C-hemHalf2+4)+'" y1="'+(hemY2-5)+'" x2="'+(C+hemHalf2-4)+'" y2="'+(hemY2-5)+'" stroke="'+stroke+'" stroke-width="1" stroke-dasharray="2 3" opacity="0.5"/>';
    parts+=detailOverlays(C,wY,hemY2,wHalf,hemHalf2,true);
  } else {
    var wY3=150,ankleY=[250,330,390,448][lenMap[design.len]];var wHalf3=design.sil=="ample"?58:46;var legBot=design.sil=="ample"?40:(design.sil=="ajustee"?18:28);var crotchY=205,gap=6,legTop=wHalf3-8;
    parts='<rect x="'+(C-wHalf3)+'" y="'+(wY3-16)+'" width="'+(wHalf3*2)+'" height="16" rx="3" fill="'+design.color+'" stroke="'+stroke+'" stroke-width="2"/>';
    parts+='<path d="M '+(C-wHalf3)+' '+wY3+' L '+(C-legBot)+' '+ankleY+' L '+(C-gap)+' '+ankleY+' L '+(C-gap)+' '+crotchY+' L '+(C-legTop)+' '+wY3+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2.2" stroke-linejoin="round"/>';
    parts+='<path d="M '+(C+wHalf3)+' '+wY3+' L '+(C+legBot)+' '+ankleY+' L '+(C+gap)+' '+ankleY+' L '+(C+gap)+' '+crotchY+' L '+(C+legTop)+' '+wY3+' Z" fill="'+pf.fill+'" stroke="'+stroke+'" stroke-width="2.2" stroke-linejoin="round"/>';
    parts+=detailOverlays(C,wY3,ankleY,wHalf3,wHalf3,false);
  }
  svg.innerHTML='<defs>'+pf.defs+'</defs>'+parts;
  var T={robe:"Robe",jupe:"Jupe",top:"Top",pantalon:"Pantalon"},S={droite:"droite",evasee:"évasée",ajustee:"ajustée",ample:"ample"},L={mini:"courte",genou:"aux genoux",midi:"midi",long:"longue"};
  var sum=T[design.type]+" "+S[design.sil]+", longueur "+L[design.len];if(topish)sum+=", encolure "+$("dNeck").options[$("dNeck").selectedIndex].text.toLowerCase()+", manches "+$("dSleeve").options[$("dSleeve").selectedIndex].text.toLowerCase();var extra=[];if(design.hem&&design.hem!="simple")extra.push("bas "+design.hem);if(design.waist&&design.waist!="aucun")extra.push(design.waist);if(design.poches)extra.push("poches");if(design.boutons)extra.push("boutons");if(design.fente)extra.push("fente");sum+=(extra.length?", "+extra.join(", "):"")+", imprimé "+design.print+" ("+design.view+").";$("designSummary").textContent=sum;window._designSummary=sum;
}
function designToCarnet(){var T={robe:"Robe",jupe:"Jupe",top:"Top",pantalon:"Pantalon"};state.projets.unshift({id:uid(),name:T[design.type]+" — mon design",piece:T[design.type],diff:"Intermédiaire",stat:"envie",tissu:(window._designSummary||""),date:""});save();renderProjets();renderCarnetStats();toast("Design ajouté au carnet");}
function designToTissu(){goView("tissu");setTissuMode("vetement");var map={robe:design.sleeve=="longue"||design.sleeve=="bishop"?"robe_ml":"robe_sm",jupe:"jupe",top:design.sleeve=="longue"||design.sleeve=="bishop"?"top_ml":"top_sm",pantalon:"pantalon"};$("gType").value=map[design.type]||"robe_sm";var len={mini:55,genou:95,midi:110,long:130}[design.len]||100;if(design.type=="top")len={mini:55,genou:62,midi:68,long:74}[design.len]||62;if(design.type=="jupe")len={mini:40,genou:55,midi:70,long:90}[design.len]||60;$("gLen").value=len;computeGarment();toast("Type de vêtement pré-rempli");}
function designToCreate(){goView("patrons");setPatMode("creer");if(design.type=="jupe"){piece="jupe";document.querySelectorAll("#pieceSeg button").forEach(function(n){n.classList.toggle("on",n.dataset.p==="jupe");});renderPatronControls();toast("Patron de jupe prêt à régler");}else{toast("Ta "+design.type+" ajustée : bibliothèque ou FreeSewing (le générateur fait les pièces simples).");}}
function designToDraw(){document.querySelectorAll("#studioMode button").forEach(function(n){n.classList.toggle("on",n.dataset.s==="draw");});$("studioCompose").style.display="none";$("studioDraw").style.display="block";initSketch();$("refSelect").value="__flat__";loadRef();toast("Décalque ton croquis et personnalise-le");}

/* ===== STUDIO dessin ===== */
var sk={ctx:null,draw:false,eraser:false,undo:[],lx:0,ly:0,init:false};
function initSketch(){if(sk.init){renderSketchPalette();return;}var cv=$("sketchCanvas");sk.ctx=cv.getContext("2d");sk.ctx.lineCap="round";sk.ctx.lineJoin="round";sketchClear(true);
  function pos(e){var r=cv.getBoundingClientRect();var cx=(e.touches?e.touches[0].clientX:e.clientX)-r.left;var cy=(e.touches?e.touches[0].clientY:e.clientY)-r.top;return {x:cx*(cv.width/r.width),y:cy*(cv.height/r.height)};}
  function down(e){e.preventDefault();pushUndo();sk.draw=true;var p=pos(e);sk.lx=p.x;sk.ly=p.y;}
  function move(e){if(!sk.draw)return;e.preventDefault();var p=pos(e);var c=sk.ctx;c.strokeStyle=sk.eraser?"#ffffff":$("brushColor").value;c.lineWidth=parseFloat($("brushSize").value)*(cv.width/(cv.getBoundingClientRect().width||cv.width));c.beginPath();c.moveTo(sk.lx,sk.ly);c.lineTo(p.x,p.y);c.stroke();sk.lx=p.x;sk.ly=p.y;}
  function up(){sk.draw=false;}
  cv.addEventListener("mousedown",down);cv.addEventListener("mousemove",move);window.addEventListener("mouseup",up);cv.addEventListener("touchstart",down,{passive:false});cv.addEventListener("touchmove",move,{passive:false});cv.addEventListener("touchend",up);
  $("brushSize").addEventListener("input",function(){$("brushOut").textContent=this.value;});
  $("eraserBtn").addEventListener("click",function(){sk.eraser=!sk.eraser;this.classList.toggle("on");this.textContent=sk.eraser?"Pinceau":"Gomme";});
  $("refSelect").addEventListener("change",loadRef);
  sk.init=true;renderSketchPalette();refreshRefSelect();}
function renderSketchPalette(){var el=$("sketchPalette");if(!el)return;el.innerHTML=state.palette.map(function(c){return '<button class="swatch" style="width:24px;height:24px;background:'+c+';cursor:pointer;" title="couleur" onclick="document.getElementById(\'brushColor\').value=\''+c+'\';"></button>';}).join("");}
function pushUndo(){try{sk.undo.push($("sketchCanvas").toDataURL("image/png"));if(sk.undo.length>15)sk.undo.shift();}catch(e){}}
function sketchUndo(){if(!sk.undo.length)return;var d=sk.undo.pop();var img=new Image();img.onload=function(){var cv=$("sketchCanvas");sk.ctx.clearRect(0,0,cv.width,cv.height);sk.ctx.drawImage(img,0,0);};img.src=d;}
function sketchClear(silent){var cv=$("sketchCanvas");sk.ctx.fillStyle="#ffffff";sk.ctx.fillRect(0,0,cv.width,cv.height);sk.undo=[];if(!silent)loadRef();}
function refreshRefSelect(){var sel=$("refSelect");if(!sel)return;var cur=sel.value;var opts='<option value="">Vierge</option><option value="__flat__">Mon croquis paramétrique (guide)</option>';state.inspirations.filter(function(x){return x.img&&x.img.indexOf("data:")===0;}).forEach(function(x){opts+='<option value="'+x.id+'">Réf : '+esc((x.title||"image").slice(0,24))+'</option>';});sel.innerHTML=opts;if(cur)sel.value=cur;}
function loadRef(){var cv=$("sketchCanvas");if(!sk.ctx)return;sk.ctx.fillStyle="#ffffff";sk.ctx.fillRect(0,0,cv.width,cv.height);sk.undo=[];var v=$("refSelect").value;if(!v)return;if(v==="__flat__"){var svgStr='<svg xmlns="http://www.w3.org/2000/svg" width="'+cv.width+'" height="'+cv.height+'" viewBox="0 0 300 470">'+$("designSvg").innerHTML+'</svg>';var blob=new Blob([svgStr],{type:"image/svg+xml"});var url=URL.createObjectURL(blob);var img=new Image();img.onload=function(){sk.ctx.globalAlpha=0.28;sk.ctx.drawImage(img,0,0,cv.width,cv.height);sk.ctx.globalAlpha=1;URL.revokeObjectURL(url);};img.src=url;return;}var insp=state.inspirations.filter(function(x){return x.id==v;})[0];if(insp&&insp.img){var im=new Image();im.onload=function(){var r=Math.min(cv.width/im.width,cv.height/im.height);var w=im.width*r,h=im.height*r;sk.ctx.globalAlpha=0.3;sk.ctx.drawImage(im,(cv.width-w)/2,(cv.height-h)/2,w,h);sk.ctx.globalAlpha=1;};im.src=insp.img;}}
function saveSketch(){var cv=$("sketchCanvas");var data;try{data=cv.toDataURL("image/jpeg",0.8);}catch(e){toast("Réf externe : impossible d'enregistrer");return;}var obj={id:uid(),title:"Mon croquis",img:data,note:"",url:"",platform:"Croquis",tags:[]};state.inspirations.unshift(obj);if(!save()){state.inspirations.shift();toast("Mémoire pleine");return;}renderInspo();refreshRefSelect();toast("Croquis enregistré dans tes inspirations");}

/* ===== PATRONS ===== */
function setPatMode(m){document.querySelectorAll("#patMode button").forEach(function(n){n.classList.toggle("on",n.dataset.m===m);});$("patBiblio").style.display=m=="biblio"?"block":"none";$("patCreer").style.display=m=="creer"?"block":"none";}
document.querySelectorAll("#patMode button").forEach(function(b){b.addEventListener("click",function(){setPatMode(b.dataset.m);});});
function importPattern(){var url=$("ptUrl").value.trim();var st=$("ptStatus"),pv=$("ptPreview");pv.innerHTML="";if(!url){toast("Colle le lien du patron");return;}if(!/^https?:\/\//.test(url))url="https://"+url;st.innerHTML='<span class="spin"></span> Récupération du patron…';fetchHtml(url).then(function(html){var m=metaFrom(html);window._pendPat={img:m.img,url:url,title:m.title,desc:m.desc};st.innerHTML=m.img?"Patron trouvé — ajuste et enregistre.":"Pas d'image trouvée, le lien sera quand même gardé.";pv.innerHTML='<div class="card" style="display:flex;gap:14px;flex-wrap:wrap;align-items:flex-start;">'+(m.img?'<img src="'+esc(m.img)+'" style="width:130px;height:130px;object-fit:cover;border-radius:10px;border:1px solid var(--line);" onerror="this.style.display=\'none\'">':'')+'<div style="flex:1;min-width:200px;"><label class="fld">Nom du patron</label><input id="ppTitle" type="text" value="'+esc((m.title||"").slice(0,90))+'"><label class="fld" style="margin-top:8px;">Détails</label><input id="ppNote" type="text" value="'+esc((m.desc||"").slice(0,140))+'"><button class="btn" style="margin-top:12px;" onclick="savePattern()">Enregistrer dans la bibliothèque</button></div></div>';}).catch(function(){window._pendPat={img:"",url:url,title:"",desc:""};st.innerHTML="Récupération impossible — enregistre quand même le lien.";pv.innerHTML='<div class="card"><label class="fld">Nom du patron</label><input id="ppTitle" type="text"><button class="btn" style="margin-top:12px;" onclick="savePattern()">Enregistrer</button></div>';});}
function savePattern(){var p=window._pendPat||{};var title=($("ppTitle")||{}).value||"Patron";var note=($("ppNote")||{}).value||"";var d=detect(title+" "+note);state.patrons.unshift({id:uid(),title:title.trim()||"Patron",img:p.img||"",note:note.trim(),url:p.url||"",type:(d.garment[0]||"")});save();$("ptUrl").value="";$("ptStatus").innerHTML="";$("ptPreview").innerHTML="";window._pendPat=null;renderPatList();toast("Patron ajouté à ta bibliothèque");}
function delPattern(id){state.patrons=state.patrons.filter(function(p){return p.id!=id;});save();renderPatList();}
function patternReperToProjet(id){var p=state.patrons.filter(function(x){return x.id==id;})[0];if(!p)return;state.projets.unshift({id:uid(),name:p.title,piece:(p.type||"Patron"),diff:"Intermédiaire",stat:"envie",tissu:"",date:""});save();renderProjets();renderCarnetStats();toast("Ajouté au carnet");}
var PATLIB=[
  {name:"Plantain (t-shirt)",brand:"Deer & Doe",type:"top",level:"Débutant",desc:"Le t-shirt gratuit emblématique pour débuter le jersey.",url:"https://deer-and-doe.fr/produit/plantain-patron-gratuit/"},
  {name:"Patrons gratuits",brand:"Mood Sewciety",type:"robe",level:"Intermédiaire",desc:"La plus grande bibliothèque gratuite : robes, tops, sacs.",url:"https://blog.moodfabrics.com/category/free-sewing-patterns/"},
  {name:"Sewing School",brand:"Peppermint Mag",type:"robe",level:"Intermédiaire",desc:"Patrons gratuits haut de gamme signés créateurs indé.",url:"https://peppermintmag.com/sewing-school/"},
  {name:"Générateur sur mesure",brand:"FreeSewing",type:"top",level:"Avancé",desc:"Open-source : entre tes mesures, sors un patron PDF perso.",url:"https://freesewing.org/designs/"},
  {name:"Patrons Fibre Mood",brand:"Mondial Tissus",type:"robe",level:"Intermédiaire",desc:"Sélection de patrons tendance, certains offerts.",url:"https://www.mondialtissus.fr/patrons/patron-de-couture/patrons-fibre-mood.html"},
  {name:"Patrons gratuits PDF",brand:"Tissus Hemmers",type:"jupe",level:"Débutant",desc:"Large choix de patrons gratuits à télécharger.",url:"https://www.tissus-hemmers.fr/patrons-de-couture-gratuits"},
  {name:"Patrons gratuits",brand:"Pop Couture",type:"top",level:"Débutant",desc:"Patrons FR gratuits, tutos illustrés pour démarrer.",url:"https://www.pop-couture.com/fr/9-patrons-gratuits"},
  {name:"Free patterns",brand:"BurdaStyle",type:"robe",level:"Intermédiaire",desc:"Classiques Burda, robes et basiques, en PDF.",url:"https://www.burdastyle.com/collections/free-patterns"},
  {name:"Printable patterns",brand:"AllFreeSewing",type:"accessoire",level:"Débutant",desc:"74+ patrons imprimables gratuits, vêtements & accessoires.",url:"https://www.allfreesewing.com/Miscellaneous-Clothing/Free-Printable-Sewing-Patterns"},
  {name:"Free patterns",brand:"So Sew Easy",type:"accessoire",level:"Débutant",desc:"Sacs, accessoires et basiques faciles, gratuits.",url:"https://so-sew-easy.com/free-sewing-patterns/"},
  {name:"100+ modern patterns",brand:"Threads Monthly",type:"jupe",level:"Débutant",desc:"Sélection de patrons modernes gratuits, bien expliqués.",url:"https://threadsmonthly.com/free-sewing-patterns/"},
  {name:"Patrons enfant gratuits",brand:"Couture Enfant",type:"enfant",level:"Débutant",desc:"Patrons gratuits pour bébés et enfants.",url:"https://www.coutureenfant.fr/en/free-patterns-for-beginners/"},
  {name:"Pantalons & basiques",brand:"Mood Sewciety",type:"pantalon",level:"Intermédiaire",desc:"Pantalons, shorts et bas faciles, gratuits.",url:"https://blog.moodfabrics.com/category/free-sewing-patterns/"},
  {name:"Vestes & manteaux",brand:"BurdaStyle",type:"manteau",level:"Avancé",desc:"Vestes et manteaux pour monter en niveau.",url:"https://www.burdastyle.com/collections/free-patterns"},
  {name:"Jupes gratuites",brand:"Peppermint Mag",type:"jupe",level:"Débutant",desc:"Jupes élégantes et accessibles, patrons offerts.",url:"https://peppermintmag.com/sewing-school/"},
  {name:"Robes d'été",brand:"Mood Sewciety",type:"robe",level:"Débutant",desc:"Robes légères faciles, parfaites pour débuter.",url:"https://blog.moodfabrics.com/category/free-sewing-patterns/"}
];
var TYPECOL={robe:"#9c5d7c",jupe:"#c08552",top:"#5b7591",pantalon:"#5b7152",manteau:"#7a6a86",accessoire:"#bd8a3e",enfant:"#cf86a4"};
var TYPELBL={robe:"Robe",jupe:"Jupe",top:"Haut",pantalon:"Pantalon",manteau:"Veste/Manteau",accessoire:"Accessoire",enfant:"Enfant"};
$("patFType").addEventListener("change",renderPatList);$("patFLevel").addEventListener("change",renderPatList);
function renderPatList(){
  var ft=$("patFType").value,fl=$("patFLevel").value;var el=$("patList");var cards=[];
  state.patrons.forEach(function(p){if(ft!="tous"&&ft!="repere"&&p.type!=ft)return;if(fl!="tous")return;var ph=p.img?'<div class="ph" style="background-image:url(\''+(p.img.indexOf("data:")===0?p.img:esc(p.img))+'\')"></div>':'<div class="ph">&#9986; patron</div>';var src=p.url?'<a href="'+esc(p.url)+'" target="_blank" rel="noopener">ouvrir le patron &#8599;</a>':'';cards.push('<div class="insp">'+ph+'<div class="bd"><div style="display:flex;justify-content:space-between;align-items:center;gap:6px;"><span class="tag typ">repéré'+(p.type?" · "+esc(p.type):"")+'</span><button class="x" onclick="delPattern('+p.id+')">&times;</button></div><h4>'+esc(p.title)+'</h4>'+(p.note?'<div class="muted" style="font-size:13px;">'+esc(p.note)+'</div>':'')+'<div style="margin-top:10px;display:flex;gap:10px;align-items:center;font-size:13px;flex-wrap:wrap;"><button class="btn ghost sm" onclick="patternReperToProjet('+p.id+')">&#8594; carnet</button>'+src+'</div></div></div>');});
  if(ft!="repere"){PATLIB.filter(function(p){return (ft=="tous"||p.type==ft)&&(fl=="tous"||p.level==fl);}).forEach(function(p){var col=TYPECOL[p.type]||"#9c5d7c";var cached=state.patImg&&state.patImg[p.url];var topStyle=cached?("background-image:url('"+esc(cached)+"');background-color:"+col+";background-size:cover;background-position:center;"):("background:"+col+";");cards.push('<div class="patcard"><div class="top" data-url="'+esc(p.url)+'" style="'+topStyle+'">'+(cached?"":esc(TYPELBL[p.type]||""))+'</div><div class="bd"><div style="font-weight:600;">'+esc(p.name)+'</div><div class="muted" style="font-size:13px;margin-bottom:6px;">'+esc(p.brand)+'</div><div style="margin-bottom:8px;"><span class="tag lvl">'+esc(p.level)+'</span></div><div class="muted" style="font-size:13px;min-height:38px;">'+esc(p.desc)+'</div><a class="btn sm" style="margin-top:10px;display:inline-block;color:#fff;text-decoration:none;" href="'+esc(p.url)+'" target="_blank" rel="noopener">Voir le patron &#8599;</a> <button class="btn ghost sm" onclick="patternToProjet('+"'"+jsq(p.name)+"','"+jsq(p.brand)+"'"+')">+ carnet</button></div></div>');});}
  if(!cards.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;">'+(ft=="repere"?"Tu n'as pas encore de patron repéré. Colle un lien ci-dessus.":"Aucun patron pour ce filtre.")+'</div>';return;}
  el.innerHTML=cards.join("");lazyThumbs();
}
function lazyThumbs(){var nodes=[].slice.call(document.querySelectorAll('#patList .top[data-url]')).filter(function(n){return !n.style.backgroundImage;});var i=0;function nx(){if(i>=nodes.length)return;var n=nodes[i++];var u=n.getAttribute("data-url");if(state.patImg&&state.patImg[u]!==undefined){if(state.patImg[u]){n.style.backgroundImage="url('"+state.patImg[u]+"')";n.textContent="";}return nx();}fetchHtml(u).then(function(h){var m=metaFrom(h);state.patImg[u]=m.img||"";if(m.img){n.style.backgroundImage="url('"+m.img+"')";n.textContent="";}save();}).catch(function(){state.patImg[u]="";}).then(function(){setTimeout(nx,180);});}nx();}
function patternToProjet(name,brand){state.projets.unshift({id:uid(),name:name,piece:brand,diff:"Intermédiaire",stat:"envie",tissu:"",date:""});save();renderProjets();renderCarnetStats();toast("Patron ajouté au carnet");}

/* ===== générateur ===== */
var piece="jupe";
var PIECES={jupe:{title:"Jupe à taille élastique",fields:[{k:"waist",l:"Tour de taille (cm)",v:72,profil:"taille"},{k:"len",l:"Longueur (cm)",v:55},{k:"full",l:"Ampleur (×)",v:1.8,step:0.1,min:1.3,max:2.6}]},tote:{title:"Tote bag",fields:[{k:"w",l:"Largeur du sac (cm)",v:38},{k:"h",l:"Hauteur du sac (cm)",v:42},{k:"anse",l:"Longueur des anses (cm)",v:60}]},coussin:{title:"Housse de coussin",fields:[{k:"cote",l:"Côté du coussin (cm)",v:45},{k:"rabat",l:"Recouvrement dos (cm)",v:15}]},taie:{title:"Taie d'oreiller",fields:[{k:"larg",l:"Largeur oreiller (cm)",v:60},{k:"haut",l:"Hauteur oreiller (cm)",v:40}]},chouchou:{title:"Chouchou",fields:[{k:"larg",l:"Largeur du tissu plié (cm)",v:11},{k:"long",l:"Longueur (cm)",v:54}]},bandeau:{title:"Bandeau cheveux",fields:[{k:"tour",l:"Tour de tête (cm)",v:56},{k:"larg",l:"Largeur du bandeau (cm)",v:10}]}};
document.querySelectorAll("#pieceSeg button").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("#pieceSeg button").forEach(function(n){n.classList.remove("on");});b.classList.add("on");piece=b.dataset.p;renderPatronControls();});});
["optSeam","optEase","optFw"].forEach(function(i){$(i).addEventListener("input",computePatron);});
function renderPatronControls(){var cfg=PIECES[piece];var prof=state.profil.mesures||{};var html='<h3 style="font-size:16px;margin-bottom:14px;">'+cfg.title+'</h3>';cfg.fields.forEach(function(f){var val=f.v;if(f.profil&&prof[f.profil])val=prof[f.profil];html+='<div style="margin-bottom:12px;"><label class="fld">'+f.l+(f.profil&&prof[f.profil]?' &middot; <span style="color:var(--accent)">depuis mon profil</span>':'')+'</label><input type="number" id="pf_'+f.k+'" value="'+val+'" step="'+(f.step||1)+'"'+(f.min?' min="'+f.min+'"':'')+(f.max?' max="'+f.max+'"':'')+'></div>';});$("patronControls").innerHTML=html;cfg.fields.forEach(function(f){$("pf_"+f.k).addEventListener("input",computePatron);});computePatron();}
function gvp(k){var e=$("pf_"+k);return e?parseFloat(e.value)||0:0;}
function computePatron(){var seam=parseFloat($("optSeam").value)||0,ease=parseFloat($("optEase").value)||0,fw=parseFloat($("optFw").value)||140;var kpi=[],cw,ch,res={};
  if(piece=="jupe"){var W=gvp("waist")+ease,L=gvp("len"),f=gvp("full");cw=Math.round((W*f)/2+seam*2);ch=Math.round(L+4+3);var metre=((cw*2<=fw)?ch:ch*2)/100;kpi=[["Largeur à couper",cw+" cm"],["Hauteur à couper",ch+" cm"],["Panneaux","2"],["Élastique",Math.round(gvp("waist")*0.92)+" cm"],["Tissu ("+fw+"cm)",metre.toFixed(2)+" m",true]];res={name:"Jupe élastique",tissu:metre.toFixed(2)+" m en "+fw+" cm"};drawRect(cw,ch,"gaine élastique","ourlet","à couper ×2");}
  else if(piece=="tote"){var w=gvp("w")+ease,h=gvp("h"),a=gvp("anse");cw=Math.round(w+seam*2);ch=Math.round(h*2+seam*2+6);var metreT=(ch+(a>0?12:0))/100;kpi=[["Largeur à couper",cw+" cm"],["Hauteur (pliée)",ch+" cm"],["Anses","2 × "+a+" cm"],["Tissu ("+fw+"cm)",metreT.toFixed(2)+" m",true]];res={name:"Tote bag",tissu:metreT.toFixed(2)+" m"};drawRect(cw,ch,"pli du fond","rabat haut","corps plié en 2");}
  else if(piece=="coussin"){var c=gvp("cote")+ease,r=gvp("rabat");cw=Math.round(c+seam*2);ch=Math.round(c*2+r+seam*2);var metreC=ch/100;kpi=[["Largeur à couper",cw+" cm"],["Hauteur (dos enveloppe)",ch+" cm"],["Type","dos portefeuille"],["Tissu ("+fw+"cm)",metreC.toFixed(2)+" m",true]];res={name:"Housse de coussin",tissu:metreC.toFixed(2)+" m"};drawRect(cw,ch,"rabat","rabat","dos qui se recouvre");}
  else if(piece=="taie"){var lg=gvp("larg")+ease,ht=gvp("haut");cw=Math.round(lg+seam*2);ch=Math.round(ht*2+seam*2+18);var metreP=ch/100;kpi=[["Largeur à couper",cw+" cm"],["Hauteur (avec rabat)",ch+" cm"],["Rabat","~ 15 cm"],["Tissu ("+fw+"cm)",metreP.toFixed(2)+" m",true]];res={name:"Taie d'oreiller",tissu:metreP.toFixed(2)+" m"};drawRect(cw,ch,"rabat intérieur","ourlet","taie portefeuille");}
  else if(piece=="bandeau"){var tt=gvp("tour"),lb=gvp("larg");cw=Math.round(tt*0.6+seam*2);ch=Math.round(lb*2+seam*2);var metreBa=ch/100;kpi=[["Largeur à couper",cw+" cm"],["Hauteur à couper",ch+" cm"],["Élastique dos","~ "+Math.round(tt*0.25)+" cm"],["Tissu",metreBa.toFixed(2)+" m",true]];res={name:"Bandeau",tissu:"chutes"};drawRect(cw,ch,"tube replié","couture","noeud ou élastique");}
  else {var lgc=gvp("larg"),loc=gvp("long");cw=Math.round(lgc*2+seam*2);ch=Math.round(loc+seam*2);var metreH=ch/100;kpi=[["Largeur à couper",cw+" cm"],["Longueur à couper",ch+" cm"],["Élastique","~ 18 cm"],["Tissu",metreH.toFixed(2)+" m",true]];res={name:"Chouchou",tissu:"chutes"};drawRect(cw,ch,"tube replié","passage élastique","tube de tissu");}
  window._patronRes=res;$("patronKpis").innerHTML=kpi.map(function(k){return '<div class="kpi'+(k[2]?' hl':'')+'"><div class="n">'+k[1]+'</div><div class="l">'+k[0]+'</div></div>';}).join("");}
function drawRect(cw,ch,topLbl,botLbl,centerLbl){var svg=$("patronSvg");var pad=46,availW=340-pad*1.4,availH=300-pad*1.3;var s=Math.min(availW/cw,availH/ch),w=cw*s,h=ch*s,x=(340-w)/2,y=(300-h)/2;var bandH=Math.min(h*0.18,26);svg.innerHTML='<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="#f3e7ee"/><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+bandH+'" fill="#9c5d7c" fill-opacity="0.22"/><rect x="'+x+'" y="'+(y+h-bandH)+'" width="'+w+'" height="'+bandH+'" fill="#9c5d7c" fill-opacity="0.12"/><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="none" stroke="#9c5d7c" stroke-width="1.5"/><line x1="'+x+'" y1="'+(y+bandH)+'" x2="'+(x+w)+'" y2="'+(y+bandH)+'" stroke="#9c5d7c" stroke-dasharray="4 3"/><line x1="'+x+'" y1="'+(y+h-bandH)+'" x2="'+(x+w)+'" y2="'+(y+h-bandH)+'" stroke="#9c5d7c" stroke-dasharray="4 3"/>'+tx(x+w/2,y+bandH/2+3,topLbl,9)+tx(x+w/2,y+h-bandH/2+3,botLbl,9)+tx(x+w/2,y+h/2+3,centerLbl,10)+tx(x+w/2,y+h+18,cw+" cm",11)+'<text x="'+(x-12)+'" y="'+(y+h/2)+'" transform="rotate(-90 '+(x-12)+' '+(y+h/2)+')" text-anchor="middle" font-size="11" fill="#8c8278" font-family="sans-serif">'+ch+' cm</text>';}
function tx(x,y,t,s){return '<text x="'+x+'" y="'+y+'" text-anchor="middle" font-size="'+s+'" fill="#6f3d56" font-family="sans-serif">'+t+'</text>';}
function patronToCarnet(){var r=window._patronRes;if(!r)return;state.projets.unshift({id:uid(),name:r.name+" (sur mesure)",piece:PIECES[piece].title,diff:"Facile",stat:"envie",tissu:r.tissu,date:""});save();renderProjets();renderCarnetStats();toast("Ajouté au carnet");}

/* ===== TISSU ===== */
function setTissuMode(m){document.querySelectorAll("#tissuMode button").forEach(function(n){n.classList.toggle("on",n.dataset.m===m);});$("tissuMatieres").style.display=m=="matieres"?"block":"none";$("tissuVetement").style.display=m=="vetement"?"block":"none";$("tissuPiece").style.display=m=="piece"?"block":"none";}
document.querySelectorAll("#tissuMode button").forEach(function(b){b.addEventListener("click",function(){setTissuMode(b.dataset.m);});});
var GARM={robe_sm:{l:"Robe sans manche",extra:20,sleeve:0,two:false},robe_ml:{l:"Robe manches longues",extra:20,sleeve:55,two:false},jupe:{l:"Jupe",extra:12,sleeve:0,two:false},jupe_longue:{l:"Jupe longue",extra:14,sleeve:0,two:false},top_sm:{l:"Top sans manche",extra:12,sleeve:0,two:false},top_ml:{l:"Top/chemise manches longues",extra:14,sleeve:50,two:false},pantalon:{l:"Pantalon",extra:14,sleeve:0,two:true},short:{l:"Short",extra:12,sleeve:0,two:true},veste:{l:"Veste",extra:25,sleeve:55,two:false},manteau:{l:"Manteau",extra:30,sleeve:60,two:false}};
["gType","gCirc","gLen","gFw","gPrice"].forEach(function(i){$(i).addEventListener("input",computeGarment);});
function computeGarment(){var g=GARM[$("gType").value]||GARM.robe_sm;var circ=parseFloat($("gCirc").value)||0,len=parseFloat($("gLen").value)||0,fw=parseFloat($("gFw").value)||140,price=parseFloat($("gPrice").value)||0;var needWidth=circ*1.05;var lengths=(needWidth>fw||g.two)?2:1;var metre=(lengths*(len+g.extra)+g.sleeve)/100;metre=Math.ceil(metre*10)/10;var cost=metre*price;$("gKpis").innerHTML=gbox(metre.toFixed(1)+" m","Tissu à acheter",true)+gbox(cost.toFixed(2)+" €","Budget tissu",true)+gbox(lengths+(lengths>1?" longueurs":" longueur"),"Disposition")+gbox(Math.round(needWidth)+" cm","Largeur à plat requise");var note="Estimation pour une "+g.l.toLowerCase()+" en "+fw+" cm de large. ";if(lengths>1&&!g.two)note+="Plus large que le tissu : deux longueurs. ";if(g.two)note+="Coupé en deux longueurs (jambes). ";if(g.sleeve)note+="Marge manches incluse. ";note+="Vérifie toujours le tableau de métrage du patron.";$("gNote").textContent=note;}
function gbox(n,l,hl){return '<div class="kpi'+(hl?' hl':'')+'"><div class="n">'+n+'</div><div class="l">'+l+'</div></div>';}
function computeTissu(){var w=parseFloat($("tW").value)||0,h=parseFloat($("tH").value)||0,n=parseFloat($("tN").value)||0,fw=parseFloat($("tFw").value)||140,seam=parseFloat($("tSeam").value)||0,price=parseFloat($("tPrice").value)||0;var cw=w+seam*2,ch=h+seam*2;var perRow=Math.max(1,Math.floor(fw/cw));var rows=Math.ceil(n/perRow);var metre=(rows*ch)/100,cout=metre*price;$("tissuKpis").innerHTML=gbox(cw.toFixed(0)+" × "+ch.toFixed(0)+" cm","Pièce avec marges")+gbox(perRow+" / largeur","Pièces côte à côte")+gbox(metre.toFixed(2)+" m","Métrage",true)+gbox(cout.toFixed(2)+" €","Budget",true);}
["tW","tH","tN","tFw","tSeam","tPrice"].forEach(function(i){$(i).addEventListener("input",computeTissu);});

/* ===== MATIÈRES ===== */
var FABRICS=[
  {n:"Popeline de coton",w:"110-130 g/m²",d:"Moyen",s:"Non",u:["robe","structure"],lv:"Débutant",de:"Lisse, facile à coudre, tenue nette. Chemises, robes."},
  {n:"Voile de coton",w:"60-90 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Intermédiaire",de:"Léger, transparent, joli tombé. Blouses, robes d'été."},
  {n:"Double gaze",w:"100-140 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Débutant",de:"Doux, gaufré, aérien. Robes, blouses, vêtements bébé."},
  {n:"Chambray",w:"120-160 g/m²",d:"Moyen",s:"Non",u:["robe","bas"],lv:"Débutant",de:"Aspect jean léger, polyvalent. Chemises, robes."},
  {n:"Lin",w:"150-200 g/m²",d:"Moyen",s:"Non",u:["robe","bas"],lv:"Débutant",de:"Respirant, se froisse, tombé vécu. Robes, pantalons."},
  {n:"Lin lavé",w:"160-220 g/m²",d:"Fluide",s:"Non",u:["robe","bas"],lv:"Débutant",de:"Plus souple que le lin brut, très agréable."},
  {n:"Viscose / Rayonne",w:"100-150 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Avancé",de:"Tombé liquide, glissant à couper. Robes fluides."},
  {n:"Crêpe",w:"120-180 g/m²",d:"Fluide",s:"Léger",u:["robe"],lv:"Intermédiaire",de:"Texture grainée, beau drapé, peu froissable."},
  {n:"Satin",w:"120-170 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Avancé",de:"Brillant, glissant. Robes du soir, doublures."},
  {n:"Mousseline",w:"50-80 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Avancé",de:"Très léger, vaporeux, délicat. Superpositions."},
  {n:"Jersey de coton",w:"140-200 g/m²",d:"Fluide",s:"Oui",u:["maille"],lv:"Intermédiaire",de:"Maille extensible, confort t-shirt. Aiguille jersey."},
  {n:"Jersey modal/viscose",w:"140-200 g/m²",d:"Fluide",s:"Oui",u:["maille"],lv:"Avancé",de:"Très doux et drapant, glissant. Tops près du corps."},
  {n:"French terry",w:"200-280 g/m²",d:"Moyen",s:"Oui",u:["maille"],lv:"Intermédiaire",de:"Envers bouclette, confort sweat léger."},
  {n:"Molleton gratté",w:"280-350 g/m²",d:"Structuré",s:"Oui",u:["maille"],lv:"Intermédiaire",de:"Chaud et douillet. Sweats, joggings."},
  {n:"Bord-côte",w:"220-300 g/m²",d:"Moyen",s:"Oui",u:["maille","accessoire"],lv:"Débutant",de:"Très élastique. Poignets, cols, ceintures."},
  {n:"Denim léger",w:"200-280 g/m²",d:"Moyen",s:"Variable",u:["bas","structure"],lv:"Intermédiaire",de:"Robuste, structurant. Jupes, robes, chemises."},
  {n:"Denim lourd",w:"330-450 g/m²",d:"Structuré",s:"Variable",u:["bas","structure"],lv:"Avancé",de:"Épais, rigide. Jeans, vestes. Aiguille jean."},
  {n:"Gabardine",w:"200-300 g/m²",d:"Moyen",s:"Léger",u:["bas","structure"],lv:"Intermédiaire",de:"Sergé serré, tenue impeccable. Pantalons, trenchs."},
  {n:"Twill / sergé",w:"180-260 g/m²",d:"Moyen",s:"Non",u:["bas","structure"],lv:"Débutant",de:"Diagonale visible, résistant. Pantalons, vestes."},
  {n:"Velours côtelé",w:"250-350 g/m²",d:"Moyen",s:"Variable",u:["bas","structure"],lv:"Intermédiaire",de:"Côtes veloutées, sens du poil à respecter."},
  {n:"Velours ras",w:"200-300 g/m²",d:"Fluide",s:"Variable",u:["robe","structure"],lv:"Avancé",de:"Doux, chatoyant, glissant. Robes habillées."},
  {n:"Laine bouillie",w:"300-400 g/m²",d:"Structuré",s:"Léger",u:["manteau","structure"],lv:"Intermédiaire",de:"Feutrée, chaude, ne s'effiloche pas. Vestes."},
  {n:"Lainage manteau",w:"350-500 g/m²",d:"Structuré",s:"Non",u:["manteau"],lv:"Avancé",de:"Épais et chaud. Manteaux, capes."},
  {n:"Tweed",w:"280-400 g/m²",d:"Structuré",s:"Non",u:["manteau","structure"],lv:"Avancé",de:"Texturé, chic. Vestes type Chanel, manteaux."},
  {n:"Néoprène / scuba",w:"250-350 g/m²",d:"Structuré",s:"Oui",u:["maille","structure"],lv:"Intermédiaire",de:"Tient le volume, effet sculptant. Robes structurées."},
  {n:"Liberty (tana lawn)",w:"60-90 g/m²",d:"Fluide",s:"Non",u:["robe"],lv:"Intermédiaire",de:"Coton fin imprimé, doux. Blouses, robes, doublures."},
  {n:"Flanelle de coton",w:"150-220 g/m²",d:"Moyen",s:"Non",u:["robe","structure"],lv:"Débutant",de:"Gratté, doux et chaud. Chemises, pyjamas."},
  {n:"Toile / canvas coton",w:"250-400 g/m²",d:"Structuré",s:"Non",u:["accessoire","structure"],lv:"Débutant",de:"Solide et rigide. Sacs, accessoires, déco."},
  {n:"Dentelle",w:"variable",d:"Fluide",s:"Variable",u:["robe"],lv:"Avancé",de:"Ajourée, délicate, à doubler. Pièces habillées."},
  {n:"Maille tricot (pull)",w:"250-400 g/m²",d:"Fluide",s:"Oui",u:["maille"],lv:"Avancé",de:"Très extensible, glisse. Pulls, cardigans."}
];
$("fabUsage").addEventListener("change",renderFabrics);$("fabDrape").addEventListener("change",renderFabrics);
function renderFabrics(){var fu=$("fabUsage").value,fd=$("fabDrape").value;var list=FABRICS.filter(function(f){return (fu=="tous"||f.u.indexOf(fu)>=0)&&(fd=="tous"||f.d==fd);});var el=$("fabricList");if(!list.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;">Aucune matière pour ce filtre.</div>';return;}el.innerHTML=list.map(function(f){return '<div class="fab"><div class="nm">'+esc(f.n)+'</div><div style="margin:6px 0;"><span class="tag lvl">'+esc(f.lv)+'</span> <span class="tag diff">tombé '+esc(f.d)+'</span></div><div class="muted" style="font-size:13px;line-height:1.5;">'+esc(f.de)+'</div><div style="font-size:12.5px;margin-top:8px;color:var(--accent-ink);">Poids '+esc(f.w)+' &middot; Stretch '+esc(f.s)+'</div><button class="btn ghost sm" style="margin-top:10px;" onclick="fabricToProjet('+"'"+jsq(f.n)+"'"+')">&#8594; carnet</button></div>';}).join("");}
function fabricToProjet(name){state.projets.unshift({id:uid(),name:"Projet en "+name,piece:"",diff:"Facile",stat:"envie",tissu:name,date:""});save();renderProjets();renderCarnetStats();toast("Idée tissu ajoutée au carnet");}

/* ===== CAPSULE ===== */
var CAT={haut:"Haut",bas:"Bas",robe:"Robe",veste:"Veste"};
function addCapsule(){var n=$("cName").value.trim();if(!n){toast("Nomme la pièce");return;}state.capsule.unshift({id:uid(),name:n,cat:$("cCat").value,color:$("cColor").value});save();$("cName").value="";renderCapsule();toast("Pièce ajoutée");}
function delCapsule(id){state.capsule=state.capsule.filter(function(c){return c.id!=id;});save();renderCapsule();}
function renderCapsule(){var c={haut:0,bas:0,robe:0,veste:0};state.capsule.forEach(function(p){c[p.cat]++;});var tenues=c.haut*c.bas+c.robe;$("capsuleStats").innerHTML=stat(state.capsule.length,"Pièces")+stat(tenues,"Tenues possibles")+stat(c.veste,"Vestes (à superposer)");var el=$("capsuleList");if(!state.capsule.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;">Ajoute tes pièces pour voir combien de tenues tu peux composer.</div>';return;}el.innerHTML=state.capsule.map(function(p){return '<div class="card" style="display:flex;align-items:center;gap:12px;"><div class="swatch" style="background:'+esc(p.color)+';width:40px;height:40px;flex-shrink:0;"></div><div style="flex:1;"><div style="font-weight:600;">'+esc(p.name)+'</div><div class="muted" style="font-size:13px;">'+CAT[p.cat]+'</div></div><button class="x" onclick="delCapsule('+p.id+')">&times;</button></div>';}).join("");}

/* ===== PROFIL ===== */
var MES=[["mTaille","taille"],["mPoitrine","poitrine"],["mHanches","hanches"],["mGenou","genou"],["mDos","dos"],["mPoignet","poignet"]];
function fillProfil(){var m=state.profil.mesures||{};MES.forEach(function(p){if(m[p[1]]!=null)$(p[0]).value=m[p[1]];});renderStyleChips();}
function saveProfil(){var m={};MES.forEach(function(p){var v=$(p[0]).value;if(v!=="")m[p[1]]=parseFloat(v);});state.profil.mesures=m;save();renderPatronControls();toast("Profil enregistré");}
function addStyle(){var v=$("styleIn").value.trim();if(!v)return;state.profil.styles=state.profil.styles||[];state.profil.styles.push(v);$("styleIn").value="";save();renderStyleChips();}
function delStyle(i){state.profil.styles.splice(i,1);save();renderStyleChips();}
function renderStyleChips(){var el=$("styleChips");var s=state.profil.styles||[];el.innerHTML=s.length?s.map(function(t,i){return '<span class="chip">'+esc(t)+' <button class="x" style="font-size:14px;padding:0 2px;" onclick="delStyle('+i+')">&times;</button></span>';}).join(""):'<span class="muted" style="font-size:13px;">Aucun mot-clé pour l\'instant.</span>';}

/* ===== DATA ===== */
function exportData(){var blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});var a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mon-atelier-couture.json";a.click();URL.revokeObjectURL(a.href);toast("Sauvegarde exportée");}
function importData(file){if(!file)return;var rd=new FileReader();rd.onload=function(){try{var d=JSON.parse(rd.result);state=Object.assign(JSON.parse(JSON.stringify(DEFAULT)),d);save();renderAll();toast("Sauvegarde importée");}catch(e){toast("Fichier illisible");}};rd.readAsText(file);}

/* ===== SHARE + PWA ===== */
function handleShared(){var qs=new URLSearchParams(location.search);var shared=qs.get("url")||qs.get("text")||qs.get("shared")||"";var m=shared.match(/https?:\/\/[^\s]+/);if(m){goView("inspirations");$("impUrl").value=m[0];importLink();}}
if("serviceWorker" in navigator){try{navigator.serviceWorker.register("sw.js").catch(function(){});}catch(e){}}
(function(){var h=$("installHint");if(location.protocol==="file:")h.textContent="Tu ouvres l'app en local : le bouton Partager natif s'activera une fois l'app hébergée et installée.";else h.textContent="App en ligne — installe-la (menu → Installer l'application) pour la voir dans le menu Partager.";})();

/* ===== INIT ===== */
function renderAll(){renderCarnetStats();renderProjets();renderPalette();renderTagFilter();renderInspo();renderPatronControls();computeTissu();computeGarment();renderFabrics();renderCapsule();fillProfil();drawDesign();renderPatList();updateAiMode();refreshRefSelect();}
renderAll();
handleShared();
